mv com.estrongs.android*.apk com.estrongs.android.apk
cp com.estrongs.android*.apk com.estrongs.android.zip
unzip -o com.estrongs.android.zip
mv guanwang*.apk guanwang.apk
cp guanwang*.apk guanwang.zip
unzip -o guanwang.zip
mv VLC-Android*.apk VLC-Android.apk
cp VLC-Android*.apk VLC-Android.zip
unzip -o VLC-Android.zip
cp lib/armeabi-v7a/* lib/armeabi/
